// Starter mock data for frontend development
// Allows the React dashboard to run fully independently before backend API is running!
// Includes dual aliases (location/city, severity/current_severity, anomaly_score/current_score)
// for seamless compatibility with all frontend components.

export const MOCK_LOCATIONS = [
  {
    location: "Bengaluru",
    city: "Bengaluru",
    lat: 12.9716,
    lon: 77.5946,
    state: "Karnataka",
    elevation: 920.0,
    severity: "CRITICAL",
    current_severity: "CRITICAL",
    active_severity_level: "CRITICAL",
    anomaly_score: 0.94,
    current_score: 0.94,
    current_anomaly_score: 0.94,
    temperature: 37.0,
    relative_humidity: 92.0,
    pressure: 994.0,
    wind_speed: 14.5,
    rainfall: 145.0,
  },
  {
    location: "Delhi",
    city: "Delhi",
    lat: 28.6139,
    lon: 77.2090,
    state: "Delhi NCR",
    elevation: 216.0,
    severity: "NORMAL",
    current_severity: "NORMAL",
    active_severity_level: "NORMAL",
    anomaly_score: 0.18,
    current_score: 0.18,
    current_anomaly_score: 0.18,
    temperature: 31.0,
    relative_humidity: 48.0,
    pressure: 1012.0,
    wind_speed: 3.2,
    rainfall: 0.0,
  },
  {
    location: "Mumbai",
    city: "Mumbai",
    lat: 19.0760,
    lon: 72.8777,
    state: "Maharashtra",
    elevation: 14.0,
    severity: "WATCH",
    current_severity: "WATCH",
    active_severity_level: "WATCH",
    anomaly_score: 0.48,
    current_score: 0.48,
    current_anomaly_score: 0.48,
    temperature: 29.5,
    relative_humidity: 82.0,
    pressure: 1004.0,
    wind_speed: 7.8,
    rainfall: 45.0,
  },
  {
    location: "Chennai",
    city: "Chennai",
    lat: 13.0827,
    lon: 80.2707,
    state: "Tamil Nadu",
    elevation: 6.0,
    severity: "NORMAL",
    current_severity: "NORMAL",
    active_severity_level: "NORMAL",
    anomaly_score: 0.22,
    current_score: 0.22,
    current_anomaly_score: 0.22,
    temperature: 32.0,
    relative_humidity: 71.0,
    pressure: 1010.0,
    wind_speed: 4.0,
    rainfall: 5.0,
  },
  {
    location: "Kolkata",
    city: "Kolkata",
    lat: 22.5726,
    lon: 88.3639,
    state: "West Bengal",
    elevation: 9.0,
    severity: "HIGH",
    current_severity: "HIGH",
    active_severity_level: "HIGH",
    anomaly_score: 0.74,
    current_score: 0.74,
    current_anomaly_score: 0.74,
    temperature: 34.5,
    relative_humidity: 88.0,
    pressure: 998.0,
    wind_speed: 11.2,
    rainfall: 68.0,
  },
  {
    location: "Hyderabad",
    city: "Hyderabad",
    lat: 17.3850,
    lon: 78.4867,
    state: "Telangana",
    elevation: 542.0,
    severity: "NORMAL",
    current_severity: "NORMAL",
    active_severity_level: "NORMAL",
    anomaly_score: 0.15,
    current_score: 0.15,
    current_anomaly_score: 0.15,
    temperature: 29.0,
    relative_humidity: 62.0,
    pressure: 1011.0,
    wind_speed: 3.5,
    rainfall: 2.0,
  },
  {
    location: "Shimla",
    city: "Shimla",
    lat: 31.1048,
    lon: 77.1734,
    state: "Himachal Pradesh",
    elevation: 2276.0,
    severity: "NORMAL",
    current_severity: "NORMAL",
    active_severity_level: "NORMAL",
    anomaly_score: 0.12,
    current_score: 0.12,
    current_anomaly_score: 0.12,
    temperature: 18.0,
    relative_humidity: 55.0,
    pressure: 1016.0,
    wind_speed: 2.8,
    rainfall: 0.0,
  },
  {
    location: "Jaipur",
    city: "Jaipur",
    lat: 26.9124,
    lon: 75.7873,
    state: "Rajasthan",
    elevation: 431.0,
    severity: "NORMAL",
    current_severity: "NORMAL",
    active_severity_level: "NORMAL",
    anomaly_score: 0.25,
    current_score: 0.25,
    current_anomaly_score: 0.25,
    temperature: 35.0,
    relative_humidity: 38.0,
    pressure: 1009.0,
    wind_speed: 4.5,
    rainfall: 0.0,
  },
  {
    location: "Ahmedabad",
    city: "Ahmedabad",
    lat: 23.0225,
    lon: 72.5714,
    state: "Gujarat",
    elevation: 53.0,
    severity: "NORMAL",
    current_severity: "NORMAL",
    active_severity_level: "NORMAL",
    anomaly_score: 0.31,
    current_score: 0.31,
    current_anomaly_score: 0.31,
    temperature: 36.0,
    relative_humidity: 45.0,
    pressure: 1008.0,
    wind_speed: 5.0,
    rainfall: 0.0,
  },
  {
    location: "Bhubaneswar",
    city: "Bhubaneswar",
    lat: 20.2961,
    lon: 85.8245,
    state: "Odisha",
    elevation: 45.0,
    severity: "WATCH",
    current_severity: "WATCH",
    active_severity_level: "WATCH",
    anomaly_score: 0.55,
    current_score: 0.55,
    current_anomaly_score: 0.55,
    temperature: 33.0,
    relative_humidity: 78.0,
    pressure: 1003.0,
    wind_speed: 6.5,
    rainfall: 35.0,
  },
];

export const MOCK_PREDICTION_RESPONSE = {
  location: "Bengaluru",
  city: "Bengaluru",
  timestamp: new Date().toISOString(),
  is_anomaly: true,
  anomaly_score: 0.94,
  current_score: 0.94,
  severity: "CRITICAL",
  current_severity: "CRITICAL",
  anomaly_type: "Compound Weather Anomaly",
  contributors: [
    { feature: "rainfall", contribution_pct: 52.4, observed: 145.0, expected: 18.2, unit: "mm", direction: "HIGH", departure: 126.8, pct_departure: 696.7, z_score: 5.4 },
    { feature: "temperature", contribution_pct: 28.1, observed: 37.0, expected: 27.1, unit: "°C", direction: "HIGH", departure: 9.9, pct_departure: 36.5, z_score: 3.8 },
    { feature: "pressure", contribution_pct: 19.5, observed: 994.0, expected: 1008.0, unit: "hPa", direction: "LOW", departure: -14.0, pct_departure: -1.4, z_score: -3.8 },
    { feature: "relative_humidity", contribution_pct: 0.0, observed: 92.0, expected: 74.0, unit: "%", direction: "HIGH", departure: 18.0, pct_departure: 24.3, z_score: 1.2 },
    { feature: "wind_speed", contribution_pct: 0.0, observed: 14.5, expected: 3.5, unit: "m/s", direction: "HIGH", departure: 11.0, pct_departure: 314.3, z_score: 2.1 },
  ],
  explanation: "CRITICAL ALERT in Bengaluru: Severe Compound Weather Anomaly detected relative to September baseline. Primary drivers: Rainfall is +697% above normal (145.0mm vs 18.2mm normal, Z=+5.4); Temperature departure of +9.9°C (37.0°C observed vs 27.1°C normal, Z=+3.8); Atmospheric Pressure departure of -14.0hPa (994.0 vs 1008.0 normal, Z=-3.8).",
  statistical_score: 0.92,
  ml_score: 0.95,
  processing_time_ms: 6.4,
};

export const MOCK_WEATHER_SUMMARY = {
  location: "Bengaluru",
  city: "Bengaluru",
  timestamp: new Date().toISOString(),
  month: 9,
  observed: {
    temperature: 37.0,
    relative_humidity: 92.0,
    pressure: 994.0,
    wind_speed: 14.5,
    rainfall: 145.0,
  },
  expected_normals: {
    temperature: 27.1,
    relative_humidity: 74.0,
    pressure: 1008.0,
    wind_speed: 3.5,
    rainfall: 18.2,
  },
  departures: {
    temperature: 9.9,
    relative_humidity: 18.0,
    pressure: -14.0,
    wind_speed: 11.0,
    rainfall: 126.8,
  },
  percentage_departures: {
    temperature: 36.5,
    relative_humidity: 24.3,
    pressure: -1.4,
    wind_speed: 314.3,
    rainfall: 696.7,
  },
  current_anomaly_score: 0.94,
  anomaly_score: 0.94,
  current_severity: "CRITICAL",
  severity: "CRITICAL",
  anomaly_type: "Compound Weather Anomaly",
  explanation: "CRITICAL ALERT in Bengaluru: Severe Compound Weather Anomaly detected relative to September baseline.",
};
